### ISSUE TITLE
write_TPL should be an exported function(?)

### ISSUE THREAD

**Issue by wStockhausen** [GMACS-project/gmr#11]
I think write_TPL should be an exported function. Any reason why not?

**Comment by MatthVeron** [comment]
I did not exported it because it is more related to creating the .exe and so, using the createGmacsExe.R or the GetGmacsExe.R function, the user does not have to use it. I try avoiding to export "unuseful" functions for the user but if you think it should be (as you did on your branch, I'll export it)

**Comment by wStockhausen** [comment]
I probably exported it so I could play around with it more easily.

*William T. Stockhausen*

Research Fishery Biologist, Alaska Fisheries Science Center

NOAA Fisheries | U.S. Department of Commerce

Office: (206) 526-4241

www.fisheries.noaa.gov

**Comment by MatthVeron** [comment]
That makes sense. I'll export it again.
